services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: finwise
      POSTGRES_USER: Franck
      POSTGRES_PASSWORD: 12345
    ports:
      - "5430:5432"

