spring:
  application:
    name: finwise-backend

  datasource:
    url: jdbc:postgresql://localhost:5430/finwise
    username: Franck
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

